from adafruit_hid.keycode import Keycode as kc

keycodeMap = {
    "A": kc.A,
    "B": kc.B,
    "C": kc.C,
    "D": kc.D,
    "E": kc.E,
    "F": kc.F,
    "G": kc.G,
    "H": kc.H,
    "I": kc.I,
    "J": kc.J,
    "K": kc.K,
    "L": kc.L,
    "M": kc.M,
    "N": kc.N,
    "O": kc.O,
    "P": kc.P,
    "Q": kc.Q,
    "R": kc.R,
    "S": kc.S,
    "T": kc.T,
    "U": kc.U,
    "V": kc.V,
    "W": kc.W,
    "X": kc.X,
    "Y": kc.Y,
    "Z": kc.Z,
    "ONE": kc.ONE,
    "1": kc.ONE,
    "TWO": kc.TWO,
    "2": kc.TWO,
    "THREE": kc.THREE,
    "3": kc.THREE,
    "FOUR": kc.FOUR,
    "4": kc.FOUR,
    "FIVE": kc.FIVE,
    "5": kc.FIVE,
    "SIX": kc.SIX,
    "6": kc.SIX,
    "SEVEN": kc.SEVEN,
    "7": kc.SEVEN,
    "EIGHT": kc.EIGHT,
    "8": kc.EIGHT,
    "NINE": kc.NINE,
    "9": kc.NINE,
    "ZERO": kc.ZERO,
    "0": kc.ZERO,
    "ENTER": kc.ENTER,
    "RETURN": kc.RETURN,
    "ESC": kc.ESCAPE,
    "ESCAPE": kc.ESCAPE,
    "BACKSPACE": kc.BACKSPACE,
    "TAB": kc.TAB,
    "SPACEBAR": kc.SPACEBAR,
    "SPACE": kc.SPACE,
    "MINUS": kc.MINUS,
    "EQUALS": kc.EQUALS,
    "LEFT_BRACKET": kc.LEFT_BRACKET,
    "RIGHT_BRACKET": kc.RIGHT_BRACKET,
    "BACKSLASH": kc.BACKSLASH,
    "POUND": kc.POUND,
    "SEMICOLON": kc.SEMICOLON,
    "QUOTE": kc.QUOTE,
    "GRAVE_ACCENT": kc.GRAVE_ACCENT,
    "COMMA": kc.COMMA,
    "PERIOD": kc.PERIOD,
    "FORWARD_SLASH": kc.FORWARD_SLASH,
    "CAPS_LOCK": kc.CAPS_LOCK,
    "F1": kc.F1,
    "F2": kc.F2,
    "F3": kc.F3,
    "F4": kc.F4,
    "F5": kc.F5,
    "F6": kc.F6,
    "F7": kc.F7,
    "F8": kc.F8,
    "F9": kc.F9,
    "F10": kc.F10,
    "F11": kc.F11,
    "F12": kc.F12,
    "PRINT_SCREEN": kc.PRINT_SCREEN,
    "SCROLL_LOCK": kc.SCROLL_LOCK,
    "PAUSE": kc.PAUSE,
    "INSERT": kc.INSERT,
    "DELETE": kc.DELETE,
    "HOME": kc.HOME,
    "END": kc.END,
    "PAGE_UP": kc.PAGE_UP,
    "PAGE_DOWN": kc.PAGE_DOWN,
    "RIGHT_ARROW": kc.RIGHT_ARROW,
    "LEFT_ARROW": kc.LEFT_ARROW,
    "DOWN_ARROW": kc.DOWN_ARROW,
    "UP_ARROW": kc.UP_ARROW,
    "KEYPAD_NUMLOCK": kc.KEYPAD_NUMLOCK,
    "KEYPAD_FORWARD_SLASH": kc.KEYPAD_FORWARD_SLASH,
    "KEYPAD_ASTERISK": kc.KEYPAD_ASTERISK,
    "KEYPAD_MINUS": kc.KEYPAD_MINUS,
    "KEYPAD_PLUS": kc.KEYPAD_PLUS,
    "KEYPAD_ENTER": kc.KEYPAD_ENTER,
    "KEYPAD_ONE": kc.KEYPAD_ONE,
    "KEYPAD_TWO": kc.KEYPAD_TWO,
    "KEYPAD_THREE": kc.KEYPAD_THREE,
    "KEYPAD_FOUR": kc.KEYPAD_FOUR,
    "KEYPAD_FIVE": kc.KEYPAD_FIVE,
    "KEYPAD_SIX": kc.KEYPAD_SIX,
    "KEYPAD_SEVEN": kc.KEYPAD_SEVEN,
    "KEYPAD_EIGHT": kc.KEYPAD_EIGHT,
    "KEYPAD_NINE": kc.KEYPAD_NINE,
    "KEYPAD_ZERO": kc.KEYPAD_ZERO,
    "KEYPAD_PERIOD": kc.KEYPAD_PERIOD,
    "KEYPAD_BACKSLASH": kc.KEYPAD_BACKSLASH,
    "KEYPAD_EQUALS": kc.KEYPAD_EQUALS,
    "APPLICATION": kc.APPLICATION,
    "POWER": kc.POWER,
    "F13": kc.F13,
    "F14": kc.F14,
    "F15": kc.F15,
    "F16": kc.F16,
    "F17": kc.F17,
    "F18": kc.F18,
    "F19": kc.F19,
    "F20": kc.F20,
    "F21": kc.F21,
    "F22": kc.F22,
    "F23": kc.F23,
    "F24": kc.F24,
    "LEFT_CONTROL": kc.LEFT_CONTROL,
    "CONTROL": kc.CONTROL,
    "LEFT_SHIFT": kc.LEFT_SHIFT,
    "SHIFT": kc.SHIFT,
    "LEFT_ALT": kc.LEFT_ALT,
    "ALT": kc.ALT,
    "OPTION": kc.OPTION,
    "LEFT_GUI": kc.LEFT_GUI,
    "GUI": kc.GUI,
    "WINDOWS": kc.WINDOWS,
    "COMMAND": kc.COMMAND,
    "RIGHT_CONTROL": kc.RIGHT_CONTROL,
    "RIGHT_SHIFT": kc.RIGHT_SHIFT,
    "RIGHT_ALT": kc.RIGHT_ALT,
    "RIGHT_GUI": kc.RIGHT_GUI
}
for e in list(keycodeMap.keys()):
    keycodeMap[e.lower()] = keycodeMap[e]

themeGroups = {
    "movement": [kc.A, kc.W, kc.D, kc.S],
    "alphas": [
        kc.A, kc.B, kc.C, kc.D, kc.E, kc.F, kc.G, kc.H, kc.I, kc.J, kc.K, kc.L,
        kc.M, kc.N, kc.O, kc.P, kc.Q, kc.R, kc.S, kc.T, kc.U, kc.V, kc.W, kc.X,
        kc.Y, kc.Z
    ],
    "nums": [
        kc.ONE, kc.TWO, kc.THREE, kc.FOUR, kc.FIVE, kc.SIX, kc.SEVEN, kc.EIGHT,
        kc.NINE, kc.ZERO
    ],
    "punctuation": [
        kc.MINUS, kc.EQUALS, kc.LEFT_BRACKET, kc.RIGHT_BRACKET, kc.BACKSLASH,
        kc.POUND, kc.SEMICOLON, kc.QUOTE, kc.GRAVE_ACCENT, kc.COMMA, kc.PERIOD,
        kc.FORWARD_SLASH
    ],
    "control": [
        kc.ENTER, kc.RETURN, kc.ESCAPE, kc.ESCAPE, kc.BACKSPACE,
        kc.PRINT_SCREEN, kc.SCROLL_LOCK, kc.PAUSE, kc.INSERT, kc.DELETE
    ],
    "whitespace": [kc.TAB, kc.SPACEBAR, kc.SPACE],
    "shift": [
        kc.CAPS_LOCK, kc.LEFT_CONTROL, kc.CONTROL, kc.LEFT_SHIFT, kc.SHIFT,
        kc.LEFT_ALT, kc.ALT, kc.OPTION, kc.LEFT_GUI, kc.GUI, kc.WINDOWS,
        kc.COMMAND, kc.RIGHT_CONTROL, kc.RIGHT_SHIFT, kc.RIGHT_ALT,
        kc.RIGHT_GUI
    ],
    "function": [
        kc.F1, kc.F2, kc.F3, kc.F4, kc.F5, kc.F6, kc.F7, kc.F8, kc.F9, kc.F10,
        kc.F11, kc.F12
    ],
    "functionHigh": [
        kc.F13, kc.F14, kc.F15, kc.F16, kc.F17, kc.F18, kc.F19, kc.F20, kc.F21,
        kc.F22, kc.F23, kc.F24
    ],
    "direction": [
        kc.HOME, kc.END, kc.PAGE_UP, kc.PAGE_DOWN, kc.RIGHT_ARROW,
        kc.LEFT_ARROW, kc.DOWN_ARROW, kc.UP_ARROW
    ],
    "numpad": [
        kc.KEYPAD_ONE, kc.KEYPAD_TWO, kc.KEYPAD_THREE, kc.KEYPAD_FOUR,
        kc.KEYPAD_FIVE, kc.KEYPAD_SIX, kc.KEYPAD_SEVEN, kc.KEYPAD_EIGHT,
        kc.KEYPAD_NINE, kc.KEYPAD_ZERO
    ],
    "numop": [
        kc.KEYPAD_FORWARD_SLASH, kc.KEYPAD_ASTERISK, kc.KEYPAD_MINUS,
        kc.KEYPAD_PLUS
    ],
    "numcontrol": [kc.KEYPAD_NUMLOCK, kc.KEYPAD_ENTER, kc.KEYPAD_EQUALS],
    "numpunct": [kc.KEYPAD_PERIOD, kc.KEYPAD_BACKSLASH]
}
